### ISSUE TITLE
Add Crossbuild for Scala 3.0

### ISSUE THREAD

**Issue by scottweaver** [scottweaver/testcontainers-for-zio#2]

**Comment by gurghet** [comment]
I have never used your software but I'm starting a fresh scala 3 project that might use it, so I could probably work on this. Anything I need to know?

**Comment by scottweaver** [comment]
I don't think there is anything crazy going on in the code so the Scala 3 changes should be very minimal.

You can use the other testcontainer cross builds for guidance.

Thanks for the help!

**Comment by gurghet** [comment]
Addressed by #17
